name: Tests
on:
  push:
    branches: 
      - master 
      - dev

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Say hello world
        shell: bash
        run: echo Welcolme to my first action !
  
  unit-test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        shell: bash
        run: make tests_run

      - name: Run coverage
        shell: bash
        run: make coverage