name: Tests
on:
  push:
    branches: 
      - master 
      - dev

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Say hello world
        shell: bash
        run: echo Welcolme to my first action !
  
  unit-test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit-tests
        shell: bash
        run: make tests_run > unit_tests_outputs
      
      - name: Upload Tests outputs 
        if: ${{always()}}
        uses: actions/upload-artifact@v2
        with:
          name: unit_tests_outputs
          path: ./unit_tests_outputs
      
      - name: Run coverage
        run: make coverage > coverage_outputs

      - name: Upload coverage outputs
        if: ${{always()}}
        uses: actions/upload-artifact@v2
        with:
          name: coverage_outputs
          path: ./coverage_outputs