name: Tests
on:
  push:
    branches: 
      - master 
      - dev

jobs:
  hello-world:
    runs-on: ubuntu-20.04

    steps:
      - name: Say Hello world
      shell: bash
      run: echo Welcolme to my first action !